language: c++
sudo: true
compiler:
  - g++-6
  - gfortran-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - cmake
      - libboost-program-options-dev
      - libboost-test-dev

before_install:
  - pip install --user cpp-coveralls

before_script:
    - gcc --version
    - gcov --version
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6
    - sudo update-alternatives --config gcc
    - gcc --version
    - gcov --version

script:
    - mkdir build
    - cd build
    - export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Coverage"
    - cmake .. ${CMAKE_EXTRA_ARGS}
    - make
    - ctest -VV

after_success:
        - coveralls -i source -i app --gcov-options '\-lp' 
