language: c++
sudo: true
compiler:
  - g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - cmake
      - libboost-program-options-dev
      - libboost-test-dev

before_install:
  - pip install --user cpp-coveralls

before_script:
    - gcc --version
    - gcov --version
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-4.9 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.9
    - sudo update-alternatives --config gcc
    - gcc --version
    - gcov --version

script:
    - export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Coverage"
    - cmake . ${CMAKE_EXTRA_ARGS}
    - make
    - ctest -VV

after_success:
        - coveralls -i source -i app --gcov-options '\-lp' 
