language: c++
sudo: require
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: ['gfortran','libboost-program-options-dev', 'libboost-test-dev', 'gcc-6', 'g++-6']


script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++ 
    - gcc -v && g++ -v && cmake --version
    - cmake . && make && make test
